POST https://127.0.0.1:8000/api/login
Content-Type: application/json

{
    "username": "admin", 
    "password": "password"
}


###


PUT https://127.0.0.1:8000/api/produits/7
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjU5NTM0NzAsImV4cCI6MTcyNTk1NzA3MCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluIn0.cDiQmewVYg4xVMnfZCAedA8_RSoyRJ27P34uVsDyM9p6cPBnG9IRMha2eQcAv0_kBa6pZk_b185_cYf59rVmklLtO64EhUvYT8V5zLb_aBpCzhRipwIWxC959o3LNnDMhZqN1OBuFY2wuOeDaLN4Umwy82_zgtZMptCnlgfQrv1RoQmoKJv-tVF-xnoonX8Hn6540DCyhsreYiE780pzrD2RCDucmRLwqtdINcIznIsQsuQlGHiVYGHGzSbo7dzTrZB70ds8MccttaMnocQ4LJOq7SdUXDSefXuxmdyZ8TUCLe3tAc_KsXGwtWZKxupGoZW7xd8RS6IL9mk0llsptQ

{
    "libelleLong": "xxx",
    "libelleCourt": "ccc",
    "referenceFournisseur": "/api/fournisseurs/1",
    "prixAchat": 100,
    "prixVente": 90,
    "stock": 15,
    "actif": true,
    "photo": "/build/images/yamaha.jpg",
    "sousCategorie": "/api/categories/2",
    "idFournisseur": "/api/fournisseurs/1"
}