POST https://127.0.0.1:8000/api/login
Content-Type: application/json

{
    "username": "admin", 
    "password": "password"
}


###


PUT https://127.0.0.1:8000/api/produits/7
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjU4ODg3MjUsImV4cCI6MTcyNTg5MjMyNSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluIn0.F5JAvUuI6seG8J1OdS8q5PmKBx461dnMDliCDdgUzCza8DnpsiXWTWnd8U_LlGn4U1Myg6QofDm_Ot7KMQaV0UOThRGWTrHci2PyB9Q70XTkNh31nJtJrJqug9tsswQTYsrS-Bxhmfbaw4pSiTFJ0-R9ZTNDwmozG2osDvhe0u-pboeb9MwonYY5GvJLcMoOb0suPZqDzcLKdVjUcOisFNgFm6woDkymoPnm87F1eiA0LfW9NAKhwbSYDelvWK8PdCLcDl7Q5IK9kG2cfeE63xmfdJj0hT1Ni4eOBaVowAW_NbwN-Tw89Syl3Ta19AoOw2-1uaH90YuGQKnk5YZ48g

{
    "libelleLong": "xxx",
    "libelleCourt": "ccc",
    "referenceFournisseur": "/api/fournisseurs/1",
    
}